all:
	-make -C server_master/
	-make -C server_alarm/
	-make -C server_device/
	-make -C server_media/
	-make -C server_user/

clean:
	-make clean -C server_master/
	-make clean -C server_alarm/
	-make clean -C server_device/
	-make clean -C server_media/
	-make clean -C server_user/